### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by joshuamartin** [alexdesignworks/devbox#1]
Update README.md file: change "6.Optionally customise Vagrant file by creating `Vagrant.local` and adding anything project-specific." to "6.Optionally customise Vagrant file by creating `Vagrantfile.local` and adding anything project-specific."

**Comment by joshuamartin** [comment]
Update README.md file: change "sh vagrant-scripts/vagrant-rebuild.sh" to "sh scripts/vagrant-rebuild.sh"

**Comment by alexdesignworks** [comment]
All fixed, thanks @joshuamartin
